### ISSUE TITLE
Idea: Remote follow widget

### ISSUE THREAD

**Issue by vanitasvitae** [Automattic/wordpress-activitypub#14]
Hi!
It would be super cool to have a remote follow widget, that users can click on to follow the blog.
Additionally this could come in handy to communicate to readers, that the blog is part of the fediverse.

Ideally the page would somewhat mimic mastodons remote follow page ([example](https://mastodon.social/users/Gargron/remote_follow)).

**Comment by pfefferle** [comment]
Good Idea! Maybe I can make it a generic template, so that it could be used as shortcode, page, widget, ...

**Comment by pfefferle** [comment]
Thanks! It is part of the „old“ OStatus protocol: http://ostatus.github.io/spec/OStatus%201.0%20Draft%202.html#anchor10

**Comment by Cambridgeport90** [comment]
keep

**Comment by averymd** [comment]
Keep, plz.

**Comment by jaschaurbach** [comment]
I am using this nice Tool at the moment - hopefully just as a workaround until we get the widget in the plugin: https://github.com/mwt/apfollow

A really great thing with this widget is of course that I can link to the blog, my personal account AND to my pixelfed account. from any website which is nice. 

You can see it in action here and here.

A universal remote follow to be configurable as a widget (with different buttons maybe) would be quite nice, no? In my idea the ActivityPlugin would make use of a plugin which only offers universal follow for AP-Services. The AP-plugin "only" would need to offer the web finger endpoints and that's it, no?

**Comment by pfefferle** [comment]
Keep!

**Comment by chriskthomas** [comment]
> I am using this nice Tool at the moment - hopefully just as a workaround until we get the widget in the plugin: https://github.com/mwt/apfollow

Me too! I just use "custom html" as a widget with
```html
<div style="text-align:center"><a href="https://apfollow.mwt.me/?user=chris&instance=chriskthomas.com" class="ap-button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2032 1536" style="margin-right:6px;vertical-align:text-top" height="14px"><path d="M923.767 256L0 789.321v213.321L738.999 576v853.321L923.767 1536zm184.768 0v213.321L1847.533 896l-738.998 426.642V1536l923.766-533.358v-213.32zm0 426.642v426.68L1478.034 896zM554.267 896l-369.536 213.321 369.536 213.321z" fill-rule="evenodd" fill="currentColor"></path></svg>ActivityPub</a></div>
```

and I then style it with custom CSS
```scss
/* AP Button */
.sidebar-primary .widget a.ap-button {
  display: inline-block;
  background: $button-color;
  color: $color-of-button-text-and-icon;
  text-decoration: none;
  font: 500 14px/32px sans-serif;
  border-radius: 4px;
  padding: 4px 18px 4px 16px;
}

.sidebar-primary .widget a.ap-button:hover {
  background: $button-hover-color;
}
```
