### ISSUE TITLE
Remote Reply doesn't work

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#720]
### Quick summary

A recent update has added a "Reply on the Fediverse" button to comments which have been made on the Fediverse and syndicated to my blog.

Pressing the button launches a modal dialogue, but the actions it contains don't work.

### Steps to reproduce

1. View the comments at https://shkspr.mobi/blog/2024/04/fixing-broken-suspend-on-pop_os/#comments
2. Clicking the reply button says "invalid" 
   * ![Screenshot showing the error.](https://github.com/Automattic/wordpress-activitypub/assets/837136/e147bdb1-7fd9-4add-bbe2-2e7207d99789)

1. View the comments on an older post at https://shkspr.mobi/blog/2023/09/why-is-it-so-hard-to-watch-foreign-tv-in-the-streaming-era/#div-comment-316308
2. Clicking the reply button shows links which do not resolve to the comment.
   * ![Screenshot of error.](https://github.com/Automattic/wordpress-activitypub/assets/837136/8f5d56e6-c520-4746-b448-d1e53e020747)
   *  This shows `https://shkspr.mobi/blog/?c=316310` but the actual comment link is https://mastodon.social/@scaseynz/111093492329755997

### What you expected to happen

Modal dialogue should have buttons that work and contain valid links.

### What actually happened

Interacting with the modal did not allow me to reply on the fediverse.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by edent** [comment]
The first issue is caused by CSS. There is a text box there, but I couldn't see it because it uses invalid colours:

```css
activitypub__dialog .activitypub-dialog__button-group input {
  background-color: var(--wp--preset--color--white);
  border: 1px solid var(--wp--preset--color--black);
  color: var(--wp--preset--color--black);
...
}
```

My theme doesn't have those `--wp--preset` variables. 

Additionally, the modal doesn't respect the dark / light mode of the theme:

![Pop up is light, background is dark.](https://github.com/Automattic/wordpress-activitypub/assets/837136/c1e5f729-3d37-4a36-bff4-92f7250de51c)

I can raise a separate bug for that if necessary?
