### ISSUE TITLE
CSS uses hard-coded variables and doesn't support dark/light mode

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#721]
### Quick summary

I'm unable to see the text box because it uses invalid colours:

```css
activitypub__dialog .activitypub-dialog__button-group input {
  background-color: var(--wp--preset--color--white);
  border: 1px solid var(--wp--preset--color--black);
  color: var(--wp--preset--color--black);
...
}
```

My theme doesn't have those `--wp--preset` variables. 

Additionally, the modal doesn't respect the dark / light mode of the theme:

![Pop up is light, background is dark.](https://github.com/Automattic/wordpress-activitypub/assets/837136/c1e5f729-3d37-4a36-bff4-92f7250de51c)

### Steps to reproduce

1. Use a theme which doesn't use Gutenberg / Blocks
2. Open the reply modal

### What you expected to happen

The pop-up should be themed as per the rest of the site.

### What actually happened

The hardcoded CSS doesn't respect dark/light mode - or many other theming options.

### Impact

One

### Available workarounds?

No but the platform is still usable
